# 任务运行期间生效；不会写回 nav2_params.yaml。
id: 1
name: base
base_mode: 1
simple_nav_node:
  nav2_profile_1_name: 慢速_梅林
  nav2_profile_1_xy_goal_tolerance: 0.03
  nav2_profile_1_yaw_goal_tolerance: 0.03
  nav2_profile_1_use_rotate_to_heading: true
  nav2_profile_1_rotate_to_goal_heading_only: true
  nav2_profile_1_yaw_hold_tolerance: 0.01
  nav2_profile_1_v_linear_min: -1.0
  nav2_profile_1_v_linear_max: 1.0
  nav2_profile_1_v_angular_min: -1.0
  nav2_profile_1_v_angular_max: 1.0
  nav2_profile_1_translation_kp: 3.0
  nav2_profile_1_translation_ki: 0.0
  nav2_profile_1_translation_kd: 0.0
  nav2_profile_1_enable_rotation: true
  nav2_profile_1_rotation_kp: 1.0
  nav2_profile_1_rotation_ki: 0.0
  nav2_profile_1_rotation_kd: 0.0
  nav2_profile_1_min_approach_linear_velocity: 0.05
  nav2_profile_1_min_approach_angular_velocity: 0.05
  nav2_profile_1_approach_velocity_scaling_dist: 0.3
  nav2_profile_1_max_velocity:
  - 1.0
  - 1.0
  - 1.0
  nav2_profile_1_min_velocity:
  - -1.0
  - -1.0
  - -1.0
  nav2_profile_1_max_accel:
  - 0.5
  - 0.5
  - 1.0
  nav2_profile_1_max_decel:
  - -0.5
  - -0.5
  - -1.0
overrides: {}
