# 任务运行期间生效；不会写回 nav2_params.yaml。
id: 3
name: pre_align
base_mode: 3
simple_nav_node:
  nav2_profile_3_name: 中档速度
  nav2_profile_3_xy_goal_tolerance: 0.01
  nav2_profile_3_yaw_goal_tolerance: 0.01
  nav2_profile_3_use_rotate_to_heading: true
  nav2_profile_3_rotate_to_goal_heading_only: true
  nav2_profile_3_yaw_hold_tolerance: 0.01
  nav2_profile_3_v_linear_min: -1.5
  nav2_profile_3_v_linear_max: 1.5
  nav2_profile_3_v_angular_min: -1.5
  nav2_profile_3_v_angular_max: 1.5
  nav2_profile_3_translation_kp: 4.0
  nav2_profile_3_translation_ki: 0.0
  nav2_profile_3_translation_kd: 0.0
  nav2_profile_3_enable_rotation: true
  nav2_profile_3_rotation_kp: 1.5
  nav2_profile_3_rotation_ki: 0.0
  nav2_profile_3_rotation_kd: 0.0
  nav2_profile_3_min_approach_linear_velocity: 0.08
  nav2_profile_3_min_approach_angular_velocity: 0.05
  nav2_profile_3_approach_velocity_scaling_dist: 0.3
  nav2_profile_3_max_velocity:
  - 1.5
  - 1.5
  - 1.5
  nav2_profile_3_min_velocity:
  - -1.5
  - -1.5
  - -1.5
  nav2_profile_3_max_accel:
  - 2.0
  - 2.0
  - 1.5
  nav2_profile_3_max_decel:
  - -2.0
  - -2.0
  - -1.5
  nav2_profile_3_pre_align_enabled: true
  nav2_profile_3_pre_align_distance: 0.5
  nav2_profile_3_pre_align_release_xy_tolerance: 0.1
  nav2_profile_3_pre_align_release_yaw_tolerance: 0.15
  nav2_profile_3_pre_align_near_adjust_timeout: 0.5
overrides: {}
